import { StepState } from './state';

export const states = [
  StepState.registered({
    description: "Intro slide",
    cameraX: -4.06,
    cameraY: 2.25,
    cameraZ: 3.00,
    targetX: -4.06,
    targetY: 2.25,
    targetZ: 0,
  }),
  StepState.registered({
    description: "Linear problem",
    cameraX: 4.09,
    cameraY: 2.25,
    cameraZ: 3.00,
    targetX: 4.09,
    targetY: 2.25,
    targetZ: 0,
  }),
  StepState.registered({
    description: "Linear problem fit",
    cameraX: 6.04,
    cameraY: 2.23,
    cameraZ: 3.00,
    targetX: 6.04,
    targetY: 2.23,
    targetZ: 0.00,
  }),
  StepState.registered({
    description: "Linear neuron",
    cameraX: 9.50,
    cameraY: 2.50,
    cameraZ: 3.30,
    targetX: 8.96,
    targetY: 2.31,
    targetZ: -0.26,
    duration: 2,
  }),
  StepState.registered({
    description: "Quadratic problem",
    cameraX: 8.09,
    cameraY: 0.01,
    cameraZ: 5.63,
    targetX: 8.08,
    targetY: 0.01,
    targetZ: -0.11,
  }),
  StepState.registered({
    description: "Quadratic neuron",
    cameraX: 8.09,
    cameraY: 0.01,
    cameraZ: 5.63,
    targetX: 8.08,
    targetY: 0.01,
    targetZ: -0.11,
  }),
  StepState.registered({
    description: "Circles dataset",
    cameraX: 15.58,
    cameraY: 0.10,
    cameraZ: 5.62,
    targetX: 15.57,
    targetY: 0.10,
    targetZ: -0.12,
  }),
]
